services:
  php81:
    build:
      context: .
    tty: true
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      - .:/workspace:cached
      - ~/.aws/:/root/.aws
    working_dir: /workspace